### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Hrishikesh7665** [GIJack/python-generate_mac#1]
Hi, Dev
You doing an awesome job I love this module, but however I found a bug in vid file reading. Sometimes it show ‘UnicodeDecodeErrorerror’  description: 'charmap' codec can't decode byte 0x9d in position xxxx (in vendor file): character maps to <undefined>.

However, I fix this bug by changing 
Line no. 31 of __init__.py (in site-packages generate_mac folde)
in_file    = open(vid_file,"r")
to
in_file    = open(vid_file,"r",encoding="utf8")

Hope this will help you in future updates.
Thank You

**Comment by NetworkJack2** [comment]
Thanks for the bug report!

This may or may not be fixable, in python 3.4 they changed how encoding works.

I will in fact take a look, and try getting a definitive answer in either case. Can you help me out and show me the file, and exact code you are using/line in the manuf file its choking on?

**Comment by Hrishikesh7665** [comment]
![Screenshot 2021-03-11 085833](https://user-images.githubusercontent.com/57979686/110731338-241bf400-8248-11eb-87ae-0869073ee1c7.png)


company_names = generate_mac.list_vendors(file_path)        #Problem Occurs In This Line


and here is the link of the file which I am using as [manuf.](https://github.com/Hrishikesh7665/MAC-GEN/blob/7c26bda696fa5ece85ad59a334fed9e7310f2022/Assets/vendors)



and [here](https://github.com/Hrishikesh7665/MAC-GEN/blob/89f8209453d4c2cbe9706a153cc06033ae43282c/Mac%20Gen.py) is my python code

**Comment by NetworkJack2** [comment]
added encoding= stanza:

https://github.com/GIJack/python-generate_mac/commit/6f80f29e2e05e4406184f55f204a7e06b43e7f3c

Thank you for reporting this bug. closing now
